
[env]
TERM = "xterm-256color"

[terminal.shell]
program = '/opt/homebrew/bin/zsh'
args = ['--login']

[window]
dimensions = { columns = 130, lines = 45 }
position = { x = 500, y = 400 }
padding = { x = 4, y = 4 }
dynamic_padding = false
decorations = "none"
startup_mode = "Windowed"
dynamic_title = false
opacity = 1

[scrolling]
history = 10000
multiplier = 8

[font]
normal = { family = 'JetBrainsMono Nerd Font Mono', style = 'Regular' }
# normal = { family = 'JetBrainsMono Nerd Font', style = 'Regular' }
# bold = { family = 'JetBrainsMono Nerd Font', style = 'Bold' }
# italic = { family = 'JetBrainsMono Nerd Font', style = 'Italic' }
size = 15
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = 'Block', blinking = 'Always' }
vi_mode_style = { shape = 'Block', blinking = 'Always' }
blink_interval = 550
blink_timeout = 5
thickness = 0.20
unfocused_hollow = false

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
	# { key = 'L', mods = 'Control', action = 'ClearLogNotice' },
	{ key = "G", mods = "Shift", mode = "Vi", action = "ScrollToBottom" },
	{ key = "B", mods = "Control", mode = "Vi", action = "ScrollPageUp" },
	{ key = "F", mods = "Control", mode = "Vi", action = "ScrollPageDown" },
	{ key = "U", mods = "Control", mode = "Vi", action = "ScrollHalfPageUp" },
	{ key = "D", mods = "Control", mode = "Vi", action = "ScrollHalfPageDown" },
	{ key = "Y", mode = "Vi", action = "Copy" },
	{ key = "Y", mode = "Vi", action = "ClearSelection" },
	{ key = "Copy", mode = "Vi", action = "ClearSelection" },
	{ key = "V", mode = "Vi", action = "ToggleNormalSelection" },
	{ key = "Key0", mods = "Command", action = "ResetFontSize" },
	{ key = "Equals", mods = "Command", action = "IncreaseFontSize" },
	{ key = "Minus", mods = "Command", action = "DecreaseFontSize" },
	{ key = "K", mods = "Command", action = "ClearHistory" },
	{ key = "V", mods = "Command", action = "Paste" },
	{ key = "C", mods = "Command", action = "Copy" },
	{ key = "C", mods = "Command", mode = "Vi", action = "ClearSelection" },
	{ key = "H", mods = "Command", action = "Hide" },
	{ key = "M", mods = "Command", action = "Minimize" },
	{ key = "Q", mods = "Command", action = "Quit" },
	{ key = "Key1", mods = "Command", chars = "\u0001\u0030" },                  # 01630a
	{ key = "Key2", mods = "Command", chars = "\u0001\u0031" },                  # 01630a
	{ key = "Key3", mods = "Command", chars = "\u0001\u0032" },                  # 01630a
	{ key = "Key4", mods = "Command", chars = "\u0001\u0033" },                  # 01630a
	{ key = "Key5", mods = "Command", chars = "\u0001\u0034" },                  # 01630a
	{ key = "Key6", mods = "Command", chars = "\u0001\u0035" },                  # 01630a
	{ key = "Key7", mods = "Command", chars = "\u0001\u0036" },                  # 01630a
	{ key = "Key8", mods = "Command", chars = "\u0001\u0037" },                  # 01630a
	{ key = "Key9", mods = "Command", chars = "\u0001\u0038" },                  # 01630a
	{ key = "N", mods = "Command", action = "SpawnNewInstance" },
	{ key = "F", mods = "Command|Control", action = "ToggleFullscreen" },
	{ key = "F", mods = "Command", action = "SearchForward" },
	{ key = "B", mods = "Command", action = "SearchBackward" },
	{ key = "T", mods = "Command", chars = "\u0001\u0063" },                     # 01630a
	{ key = "D", mods = "Command", chars = "\u0001\u0025" },                     # 01630a
	{ key = "D", mods = "Command|Shift", chars = "\u0001\u002d" },               # 01630a
	{ key = "Up", mods = "Command", chars = "\u0001\u001b\u005b\u0041" },        # \x01\x70
	{ key = "Down", mods = "Command", chars = "\u0001\u001b\u005b\u0042" },      # \x01\x70
	{ key = "Right", mods = "Command", chars = "\u0001\u001b\u005b\u0043" },     # \x01\x70
	{ key = "Left", mods = "Command", chars = "\u0001\u001b\u005b\u0044" },      # \x01\x70
	{ key = "P", mods = "Command|Shift", chars = "\u0001\u0070" },               # \x01\x70
	{ key = "P", mods = "Command", chars = "\u0001\u006e" },                     # 01630a
	{ key = "Comma", mods = "Command", chars = "\u0001\u002c" },                 # 01630a
]

[general]

live_config_reload = true
import = [
	# "~/.config/alacritty/rose-pine.toml",
	"~/.config/alacritty/gruvbox.toml",
]

[terminal]
