concurrency:
    cancel-in-progress: true
    group: ${{ github.workflow }}-${{ github.ref }}
defaults:
    run:
        shell: bash
jobs:
    build-docker:
        env:
            CONTAINER_IMAGE_NAME: https://beta-api.openregistry.dev/jsdp/dotfiles:${{ github.sha }}
        name: Build Container image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the branch
              uses: actions/checkout@v4
            - id: buildx
              name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                install: true
                version: latest
            - name: Login to OpenRegistry
              uses: docker/login-action@v3
              with:
                password: ${{ secrets.GITHUB_TOKEN }}
                registry: https://beta-api.openregistry.dev
                username: jsdp
            - name: Build image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: Dockerfile
                platforms: linux/amd64
                push: true
                tags: ${{ env.CONTAINER_IMAGE_NAME }}
                target: runner
name: Build Container Image
"on":
    - push
    - pull_request
